export const f2lCases = [
  { id: 1, code: 'F01', image: '/magic_cube_web/images/f2l/F01.png', algorithm: "U R U' R'"},
  { id: 2, code: 'F02', image: '/magic_cube_web/images/f2l/F02.png', algorithm: "y U' L' U L", detail: '' },
  { id: 3, code: 'F03', image: '/magic_cube_web/images/f2l/F03.png', algorithm: "y L' U' L", detail: '' },
  { id: 4, code: 'F04', image: '/magic_cube_web/images/f2l/F04.png', algorithm: "R U R'", detail: '' },
  { id: 5, code: 'F05', image: '/magic_cube_web/images/f2l/F05.png', algorithm: "U' R U R' U2 R U' R'", detail: '' },
  { id: 6, code: 'F06', image: '/magic_cube_web/images/f2l/F06.png', algorithm: "y U L' U' L U2 L' U L", detail: '' },
  { id: 7, code: 'F07', image: '/magic_cube_web/images/f2l/F07.png', algorithm: "U' R U2 R' U2 R U' R'", detail: '' },
  { id: 8, code: 'F08', image: '/magic_cube_web/images/f2l/F08.png', algorithm: "y U L' U2 L U2 L' U L", detail: '' },
  { id: 9, code: 'F09', image: '/magic_cube_web/images/f2l/F09.png', algorithm: "U' R U' R' U y L' U' L", detail: '' },
  { id: 10, code: 'F10', image: '/magic_cube_web/images/f2l/F10.png', algorithm: "U' R U R' U R U R'", detail: '' },
  { id: 11, code: 'F11', image: '/magic_cube_web/images/f2l/F11.png', algorithm: "y' R U2 R2 U' R2 U' R'", detail: '' },
  { id: 12, code: 'F12', image: '/magic_cube_web/images/f2l/F12.png', algorithm: "R U' R' U R U' R' U2 R U' R'", detail: '' },
  { id: 13, code: 'F13', image: '/magic_cube_web/images/f2l/F13.png', algorithm: "y' U R' U R U' R' U' R", detail: '' },
  { id: 14, code: 'F14', image: '/magic_cube_web/images/f2l/F14.png', algorithm: "U' R U' R' U R U R'", detail: '' },
  { id: 15, code: 'F15', image: '/magic_cube_web/images/f2l/F15.png', algorithm: "R U R' U2 R U' R' U R U' R'", detail: '' },
  { id: 16, code: 'F16', image: '/magic_cube_web/images/f2l/F16.png', algorithm: "R U' R' U2 y' R' U' R", detail: '' },
  { id: 17, code: 'F17', image: '/magic_cube_web/images/f2l/F17.png', algorithm: "R U2 R' U' R U R'", detail: '' },
  { id: 18, code: 'F18', image: '/magic_cube_web/images/f2l/F18.png', algorithm: "y L' U2 L U L' U' L", detail: '' },
  { id: 19, code: 'F19', image: '/magic_cube_web/images/f2l/F19.png', algorithm: "U R U2 R' U R U' R'", detail: '' },
  { id: 20, code: 'F20', image: '/magic_cube_web/images/f2l/F20.png', algorithm: "y U' L' U2 L U' L' U L", detail: '' },
  { id: 21, code: 'F21', image: '/magic_cube_web/images/f2l/F21.png', algorithm: "U2 R U R' U R U' R'", detail: '' },
  { id: 22, code: 'F22', image: '/magic_cube_web/images/f2l/F22.png', algorithm: "r U' r' U2 r U r'", detail: '' },
  { id: 23, code: 'F23', image: '/magic_cube_web/images/f2l/F23.png', algorithm: "U R U' R' U' R U' R' U R U' R'", detail: '' },
  { id: 24, code: 'F24', image: '/magic_cube_web/images/f2l/F24.png', algorithm: "y U' L' U L U L' U L U' L' U L", detail: '' },
  { id: 25, code: 'F25', image: '/magic_cube_web/images/f2l/F25.png', algorithm: "U' R' F R F' R U R'", detail: '' },
  { id: 26, code: 'F26', image: '/magic_cube_web/images/f2l/F26.png', algorithm: "U R U' R' y U' L' U L", detail: '' },
  { id: 27, code: 'F27', image: '/magic_cube_web/images/f2l/F27.png', algorithm: "R U' R' U R U' R'", detail: '' },
  { id: 28, code: 'F28', image: '/magic_cube_web/images/f2l/F28.png', algorithm: "y L' U L U' L' U L", detail: '' },
  { id: 29, code: 'F29', image: '/magic_cube_web/images/f2l/F29.png', algorithm: "y L' U' L U L' U' L", detail: '' },
  { id: 30, code: 'F30', image: '/magic_cube_web/images/f2l/F30.png', algorithm: "R U R' U' R U R'", detail: '' },
  { id: 31, code: 'F31', image: '/magic_cube_web/images/f2l/F31.png', algorithm: "U' R' F R F' R U' R'", detail: '' },
  { id: 32, code: 'F32', image: '/magic_cube_web/images/f2l/F32.png', algorithm: "R U R' U' R U R' U' R U R'", detail: '' },
  { id: 33, code: 'F33', image: '/magic_cube_web/images/f2l/F33.png', algorithm: "U' R U' R' U2 R U' R'", detail: '' },
  { id: 34, code: 'F34', image: '/magic_cube_web/images/f2l/F34.png', algorithm: "U R U R' U2 R U R'", detail: ''  },
  { id: 35, code: 'F35', image: '/magic_cube_web/images/f2l/F35.png', algorithm: "U' R U R' U y L' U' L", detail: '' },
  { id: 36, code: 'F36', image: '/magic_cube_web/images/f2l/F36.png', algorithm: "y U L' U' L U' y' R U R'", detail: '' },
  { id: 37, code: 'F37', image: '/magic_cube_web/images/f2l/F37.png', algorithm: "R' F R F' R U' R' U R U' R' U2 R U' R'", detail: '' },
  { id: 38, code: 'F38', image: '/magic_cube_web/images/f2l/F38.png', algorithm: "R U' R' U' R U R' U2 R U' R'", detail: '' },
  { id: 39, code: 'F39', image: '/magic_cube_web/images/f2l/F39.png', algorithm: "R U' R' U R U2 R' U R U' R'", detail: '' },
  { id: 40, code: 'F40', image: '/magic_cube_web/images/f2l/F40.png', algorithm: "R U' R' U' R U' R' U y' R' U' R", detail: '' },
  { id: 41, code: 'F41', image: '/magic_cube_web/images/f2l/F41.png', algorithm: "R U' R' U2 y' R' U' R U' R' U R", detail: '' },
];
