export const ollCases = [
    { id: 1, code: 'O01', image: '/magic_cube_web/images/oll/O01.png', algorithm: "R U2 R2 F R F' U2 R' F R F'", detail: '' },
    { id: 2, code: 'O02', image: '/magic_cube_web/images/oll/O02.png', algorithm: "F R U R' U' S R U R' U' Fw'", detail: '' },
    { id: 3, code: 'O03', image: '/magic_cube_web/images/oll/O03.png', algorithm: "Fw R U R' U' Fw' U' F R U R' U' F'", detail: '' },
    { id: 4, code: 'O04', image: '/magic_cube_web/images/oll/O04.png', algorithm: "Fw R U R' U' Fw' U F R U R' U' F'", detail: '' },
    { id: 5, code: 'O05', image: '/magic_cube_web/images/oll/O05.png', algorithm: "Rw' U2 R U R' U Rw", detail: '' },
    { id: 6, code: 'O06', image: '/magic_cube_web/images/oll/O06.png', algorithm: "Rw U2 R' U' R U' Rw'", detail: '' },
    { id: 7, code: 'O07', image: '/magic_cube_web/images/oll/O07.png', algorithm: "Rw U R' U R U2 Rw'", detail: '' },
    { id: 8, code: 'O08', image: '/magic_cube_web/images/oll/O08.png', algorithm: "Rw' U' R U' R' U2 Rw", detail: '' },
    { id: 9, code: 'O09', image: '/magic_cube_web/images/oll/O09.png', algorithm: "R U R' U' R' F R2 U R' U' F'", detail: '' },
    { id: 10, code: 'O10', image: '/magic_cube_web/images/oll/O10.png', algorithm: "R U R' U R' F R F' R U2 R'", detail: '' },
    { id: 11, code: 'O11', image: '/magic_cube_web/images/oll/O11.png', algorithm: "Rw' R2 U R' U R U2 R' U M'", detail: '' },
    { id: 12, code: 'O12', image: '/magic_cube_web/images/oll/O12.png', algorithm: "Lw L2 U' L U' L' U2 L U' M'", detail: '' },
    { id: 13, code: 'O13', image: '/magic_cube_web/images/oll/O13.png', algorithm: "F U R U' R2 F' R U R U' R'", detail: '' },
    { id: 14, code: 'O14', image: '/magic_cube_web/images/oll/O14.png', algorithm: "R' F R U R' F' R y' R U' R'", detail: '' },
    { id: 15, code: 'O15', image: '/magic_cube_web/images/oll/O15.png', algorithm: "Rw' U' Rw R' U' R U Rw' U Rw", detail: '' },
    { id: 16, code: 'O16', image: '/magic_cube_web/images/oll/O16.png', algorithm: "Rw U Rw' R U R' U' Rw U' Rw'", detail: '' },
    { id: 17, code: 'O17', image: '/magic_cube_web/images/oll/O17.png', algorithm: "R U R' U R' F R F' U2 R' F R F'", detail: '' },
    { id: 18, code: 'O18', image: '/magic_cube_web/images/oll/O18.png', algorithm: "R U2 R2 F R F' U2 M' U R U' Rw'", detail: '' },
    { id: 19, code: 'O19', image: '/magic_cube_web/images/oll/O19.png', algorithm: "M U R U R' U' M' R' F R F'", detail: '' },
    { id: 20, code: 'O20', image: '/magic_cube_web/images/oll/O20.png', algorithm: "Rw U R' U' M2 U R U' R' U' M'", detail: '' },
    { id: 21, code: 'O21', image: '/magic_cube_web/images/oll/O21.png', algorithm: "R U2 R' U' R U R' U' R U' R'", detail: '' },
    { id: 22, code: 'O22', image: '/magic_cube_web/images/oll/O22.png', algorithm: "R U2 R2 U' R2 U' R2 U2 R", detail: '' },
    { id: 23, code: 'O23', image: '/magic_cube_web/images/oll/O23.png', algorithm: "R2 D' R U2 R' D R U2 R", detail: '' },
    { id: 24, code: 'O24', image: '/magic_cube_web/images/oll/O24.png', algorithm: "R' U' R' D' R U R' D R2", detail: '' },
    { id: 25, code: 'O25', image: '/magic_cube_web/images/oll/O25.png', algorithm: "R U2 R D R' U2 R D' R2", detail: '' },
    { id: 26, code: 'O26', image: '/magic_cube_web/images/oll/O26.png', algorithm: "R' U' R U' R' U2 R", detail: '' },
    { id: 27, code: 'O27', image: '/magic_cube_web/images/oll/O27.png', algorithm: "L U L' U L U2 L'", detail: '' },
    { id: 28, code: 'O28', image: '/magic_cube_web/images/oll/O28.png', algorithm: "Rw U R' U' M U R U' R'", detail: '' },
    { id: 29, code: 'O29', image: '/magic_cube_web/images/oll/O29.png', algorithm: "R U R' U' R U' R' F' U' F R U R'", detail: '' },
    { id: 30, code: 'O30', image: '/magic_cube_web/images/oll/O30.png', algorithm: "F R' F R2 U' R' U' R U R' F2", detail: '' },
    { id: 31, code: 'O31', image: '/magic_cube_web/images/oll/O31.png', algorithm: "R' U' F U R U' R' F' R", detail: '' },
    { id: 32, code: 'O32', image: '/magic_cube_web/images/oll/O32.png', algorithm: "R U2 R' U' F' U F R U' R'", detail: '' },
    { id: 33, code: 'O33', image: '/magic_cube_web/images/oll/O33.png', algorithm: "R U R' U' R' F R F'", detail: '' },
    { id: 34, code: 'O34', image: '/magic_cube_web/images/oll/O34.png', algorithm: "R U R2 U' R' F R U R U' F'", detail: '' },
    { id: 35, code: 'O35', image: '/magic_cube_web/images/oll/O35.png', algorithm: "R U2 R2 F R F' R U2 R'", detail: '' },
    { id: 36, code: 'O36', image: '/magic_cube_web/images/oll/O36.png', algorithm: "L' U' L U' L' U L U L F' L' F", detail: '' },
    { id: 37, code: 'O37', image: '/magic_cube_web/images/oll/O37.png', algorithm: "F R U' R' U' R U R' F'", detail: '' },
    { id: 38, code: 'O38', image: '/magic_cube_web/images/oll/O38.png', algorithm: "R U R' U R U' R' U' R' F R F'", detail: '' },
    { id: 39, code: 'O39', image: '/magic_cube_web/images/oll/O39.png', algorithm: "R U R' F' U' F U R U2 R'", detail: '' },
    { id: 40, code: 'O40', image: '/magic_cube_web/images/oll/O40.png', algorithm: "R' F R U R' U' F' U R", detail: '' },
    { id: 41, code: 'O41', image: '/magic_cube_web/images/oll/O41.png', algorithm: "R U R' U R U2 R' F R U R' U' F'", detail: '' },
    { id: 42, code: 'O42', image: '/magic_cube_web/images/oll/O42.png', algorithm: "R' U' R U' R' U2 R F R U R' U' F'", detail: '' },
    { id: 43, code: 'O43', image: '/magic_cube_web/images/oll/O43.png', algorithm: "R' U' F' U F R", detail: '' },
    { id: 44, code: 'O44', image: '/magic_cube_web/images/oll/O44.png', algorithm: "Fw R U R' U' Fw'", detail: '' },
    { id: 45, code: 'O45', image: '/magic_cube_web/images/oll/O45.png', algorithm: "F R U R' U' F'", detail: '' },
    { id: 46, code: 'O46', image: '/magic_cube_web/images/oll/O46.png', algorithm: "R' U' R' F R F' U R", detail: '' },
    { id: 47, code: 'O47', image: '/magic_cube_web/images/oll/O47.png', algorithm: "F' L' U' L U L' U' L U F", detail: '' },
    { id: 48, code: 'O48', image: '/magic_cube_web/images/oll/O48.png', algorithm: "F R U R' U' R U R' U' F'", detail: '' },
    { id: 49, code: 'O49', image: '/magic_cube_web/images/oll/O49.png', algorithm: "Rw U' Rw2 U Rw2 U Rw2 U' Rw", detail: '' },
    { id: 50, code: 'O50', image: '/magic_cube_web/images/oll/O50.png', algorithm: "Rw' U Rw2 U' Rw2 U' Rw2 U Rw'", detail: '' },
    { id: 51, code: 'O51', image: '/magic_cube_web/images/oll/O51.png', algorithm: "F U R U' R' U R U' R' F'", detail: '' },
    { id: 52, code: 'O52', image: '/magic_cube_web/images/oll/O52.png', algorithm: "R' F' U' F U' R U R' U R", detail: '' },
    { id: 53, code: 'O53', image: '/magic_cube_web/images/oll/O53.png', algorithm: "Rw' U' R U' R' U R U' R' U2 Rw", detail: '' },
    { id: 54, code: 'O54', image: '/magic_cube_web/images/oll/O54.png', algorithm: "Rw U R' U R U' R' U R U2 Rw'", detail: '' },
    { id: 55, code: 'O55', image: '/magic_cube_web/images/oll/O55.png', algorithm: "R' F R U R U' R2 F' R2 U' R' U R U R'", detail: '' },
    { id: 56, code: 'O56', image: '/magic_cube_web/images/oll/O56.png', algorithm: "Rw U Rw' U R U' R' U R U' R' Rw U' Rw'", detail: '' },
    { id: 57, code: 'O57', image: '/magic_cube_web/images/oll/O57.png', algorithm: "R U R' U' M' U R U' Rw'", detail: '' },
];
