export const pllCases = [
    { id: 1, code: 'Aa', image: '/magic_cube_web/images/pll/Aa-Perm.png', algorithm: "x R' D R' U2 R D' R' U2 R2 x'", detail: '' },
    { id: 2, code: 'Ab', image: '/magic_cube_web/images/pll/Ab-Perm.png', algorithm: "x' R D' R U2 R' D R U2 R2 x", detail: '' },
    { id: 3, code: 'E', image: '/magic_cube_web/images/pll/E-Perm.png', algorithm: "x' R U' R' D R U R' D' R U R' D R U' R' D' x", detail: '' },
    { id: 4, code: 'F', image: '/magic_cube_web/images/pll/F-Perm.png', algorithm: "R' U2 R' d' R' F' R2 U' R' U R' F R F", detail: '' },
    { id: 5, code: 'Ga', image: '/magic_cube_web/images/pll/Ga-Perm.png', algorithm: "R2 U R' U R' U' R U' R2 D U' R U R' D'", detail: '' },
    { id: 6, code: 'Gb', image: '/magic_cube_web/images/pll/Gb-Perm.png', algorithm: "R' U' R U D' R2 U R' U R U' R U' R2 D", detail: '' },
    { id: 7, code: 'Gc', image: '/magic_cube_web/images/pll/Gc-Perm.png', algorithm: "R2 U' R U' R U R' U R2 D' U R' U' R D", detail: '' },
    { id: 8, code: 'Gd', image: '/magic_cube_web/images/pll/Gd-Perm.png', algorithm: "R U R' U' D R2 U' R U' R' U R' U R2 D'", detail: '' },
    { id: 9, code: 'H', image: '/magic_cube_web/images/pll/H-Perm.png', algorithm: "M2 U M2 U2 M2 U M2", detail: '' },
    { id: 10, code: 'Ja', image: '/magic_cube_web/images/pll/Ja-Perm.png', algorithm: "x R2 F R F' R U2 r' U r U2 x'", detail: '' },
    { id: 11, code: 'Jb', image: '/magic_cube_web/images/pll/Jb-Perm.png', algorithm: "R U R' F' R U R' U' R' F R2 U' R' U'", detail: '' },
    { id: 12, code: 'Na', image: '/magic_cube_web/images/pll/Na-Perm.png', algorithm: "L U' R U2 L' U R' L U' R U2 L' U R'", detail: '' },
    { id: 13, code: 'Nb', image: '/magic_cube_web/images/pll/Nb-Perm.png', algorithm: "R' U L' U2 R U' L R' U L' U2 R U' L", detail: '' },
    { id: 14, code: 'Ra', image: '/magic_cube_web/images/pll/Ra-Perm.png', algorithm: "R U' R' U' R U R D R' U' R D' R' U2 R'", detail: '' },
    { id: 15, code: 'Rb', image: '/magic_cube_web/images/pll/Rb-Perm.png', algorithm: "R2 F R U R U' R' F' U' R' F R F'", detail: '' },
    { id: 16, code: 'T', image: '/magic_cube_web/images/pll/T-Perm.png', algorithm: "R U R' U' R' F R2 U' R' U' R U R' F'", detail: '' },
    { id: 17, code: 'Ua', image: '/magic_cube_web/images/pll/Ua-Perm.png', algorithm: "R U' R U R U R U' R' U' R2", detail: '' },
    { id: 18, code: 'Ub', image: '/magic_cube_web/images/pll/Ub-Perm.png', algorithm: "R2 U R U R' U' R' U' R' U R'", detail: '' },
    { id: 19, code: 'V', image: '/magic_cube_web/images/pll/V-Perm.png', algorithm: "R' U R' d' R' F' R2 U' R' U R' F R F", detail: '' },
    { id: 20, code: 'Y', image: '/magic_cube_web/images/pll/Y-Perm.png', algorithm: "F R U' R' U' R U R' F' R U R' U' R' F R F'", detail: '' },
    { id: 21, code: 'Z', image: '/magic_cube_web/images/pll/Z-Perm.png', algorithm: "M2 U M2 U M' U2 M2 U2 M' U2", detail: '' },
];
